-- | Export an Eidos theory to Lean 4 using the "all Props" strategy.
--
-- Handles propositional (ℙ-sorted), mereological (𝕌-sorted), and mixed
-- theories uniformly.  Both kinds of signature object are always emitted.
-- The four bound objects and the three ordering axioms linking them are
-- always present:
--
-- @
--   axiom U_Min : Prop
--   axiom U_Max : Prop
--   axiom _Top  : Prop    -- = ℙ#min
--   axiom _Bot  : Prop    -- = ℙ#max
--   -- ordering: U_Max ≤ _Bot ≤ _Top ≤ U_Min
--   axiom sort_order_1: U_Max → _Bot
--   axiom sort_order_2: _Bot  → _Top
--   axiom sort_order_3: _Top  → U_Min
-- @
--
-- 𝕌-kinded objects get boundedness axioms @P → U_Min@ and @U_Max → P@.
-- ℙ-kinded objects get boundedness axioms @P → _Top@  and @_Bot → P@.
--
-- The mereological difference operation @A - B@ is rendered as @B → A@
-- (operand swap).  All other operations (+, ×, ∸) map to (∧, ∨, ↔).
--
-- Facts from both @FactKindAssertion@ and @FactKindMetafactsFact@ are
-- emitted; assertions are wrapped with @_Top@, metafacts with @U_Min@.
module Eidos.Export.LeanProps
  ( exportToLeanProps
  ) where

import Data.List (intercalate)
import qualified Eidos.IR as IR

-- ---------------------------------------------------------------------------
-- Top-level entry point
-- ---------------------------------------------------------------------------

exportToLeanProps :: IR.Theory -> String
exportToLeanProps theory =
  unlines $
       header
    ++ userSortLimitDecls
    ++ mereoDecls
    ++ propDecls
    ++ mereoBoundsAxioms
    ++ propBoundsAxioms
    ++ userSortSetBoundsAxioms
    ++ sortOrderAxioms
    ++ userFactAxioms
  where
    -- -----------------------------------------------------------------------
    -- Header
    -- -----------------------------------------------------------------------
    header =
      [ "-- Generated by Eidos compiler"
      , "-- Theory: " ++ IR.theoryFullyQualifiedName theory
      , ""
      , "-- Bound objects"
      , "axiom U_Min : Prop"
      , "axiom U_Max : Prop"
      , "axiom _Top  : Prop"
      , "axiom _Bot  : Prop"
      , ""
      ]

    -- -----------------------------------------------------------------------
    -- 𝕌-kinded (mereological) signature objects
    -- -----------------------------------------------------------------------
    mereoObjects :: [IR.MereologicalObject]
    mereoObjects =
      [ m
      | IR.EntityMereological m <- IR.theoryObjects theory
      , IR.mereoKind m == IR.MereologicalEntityKindMereological
      , IR.mereoOrigin m == IR.FromSignature
      , IR.mereoName m `notElem` ["U_Min", "U_Max", "⊤", "⊥"]
      ]

    mereoDecls = map (\m -> "axiom " ++ IR.mereoName m ++ " : Prop") mereoObjects

    mereoBoundsAxioms = concatMap mereoBoundsFor mereoObjects

    mereoBoundsFor :: IR.MereologicalObject -> [String]
    mereoBoundsFor m =
      let n = IR.mereoName m
      in [ "axiom " ++ n ++ "_min: " ++ n ++ " → U_Min"
         , "axiom " ++ n ++ "_max: U_Max → " ++ n
         ]

    -- -----------------------------------------------------------------------
    -- ℙ-kinded (propositional) signature objects
    -- -----------------------------------------------------------------------
    propObjects :: [IR.MereologicalObject]
    propObjects =
      [ m
      | IR.EntityMereological m <- IR.theoryObjects theory
      , IR.mereoKind m == IR.MereologicalEntityKindProposition
      , IR.mereoOrigin m == IR.FromSignature
      , IR.mereoName m `notElem` ["_Top", "_Bot", "⊤", "⊥", "ℙ#min", "ℙ#max"]
      ]

    propDecls = map (\m -> "axiom " ++ IR.mereoName m ++ " : Prop") propObjects

    propBoundsAxioms = concatMap propBoundsFor propObjects

    propBoundsFor :: IR.MereologicalObject -> [String]
    propBoundsFor m =
      let n = IR.mereoName m
      in [ "axiom " ++ n ++ "_top: " ++ n ++ " → _Top"
         , "axiom " ++ n ++ "_bot: _Bot → " ++ n
         ]

    -- -----------------------------------------------------------------------
    -- User-declared sorts: declare their min/max limit objects and emit
    -- bounds axioms for every set that lives inside one of those sorts.
    -- -----------------------------------------------------------------------

    -- User sorts (excluding the three built-ins 𝕌, 𝔻, ℙ)
    userSorts :: [IR.Sort]
    userSorts =
      [ s
      | IR.EntitySort s <- IR.theoryObjects theory
      , IR.sortKind s == IR.SortKindFromSignature
      ]

    -- Lean name for a sort's lower limit (S#min → "S_Min")
    sortMinName :: IR.Sort -> String
    sortMinName s = IR.sortName s ++ "_Min"

    -- Lean name for a sort's upper limit (S#max → "S_Max")
    sortMaxName :: IR.Sort -> String
    sortMaxName s = IR.sortName s ++ "_Max"

    -- "axiom S_Min : Prop" / "axiom S_Max : Prop" for each user sort
    userSortLimitDecls :: [String]
    userSortLimitDecls = concatMap sortLimitDecls userSorts
      where
        sortLimitDecls s =
          [ "axiom " ++ sortMinName s ++ " : Prop"
          , "axiom " ++ sortMaxName s ++ " : Prop"
          ]

    -- Sets declared against user sorts (MereologicalEntityKindSet, FromSignature)
    userSortSets :: [IR.MereologicalObject]
    userSortSets =
      [ m
      | IR.EntityMereological m <- IR.theoryObjects theory
      , IR.mereoKind m == IR.MereologicalEntityKindSet
      , IR.mereoOrigin m == IR.FromSignature
      , IR.sortKind (IR.mereoSort m) == IR.SortKindFromSignature
      ]

    -- "axiom MySet_top: MySet → S_Min" / "axiom MySet_bot: S_Max → MySet"
    userSortSetBoundsAxioms :: [String]
    userSortSetBoundsAxioms = concatMap setBounds userSortSets
      where
        setBounds m =
          let n    = IR.mereoName m
              sMin = sortMinName (IR.mereoSort m)
              sMax = sortMaxName (IR.mereoSort m)
          in [ "axiom " ++ n ++ "_top: " ++ n ++ " → " ++ sMin
             , "axiom " ++ n ++ "_bot: " ++ sMax ++ " → " ++ n
             ]

    -- -----------------------------------------------------------------------
    -- Sort-ordering axioms: U_Min ≤ _Top ≤ _Bot ≤ U_Max
    -- -----------------------------------------------------------------------
    sortOrderAxioms =
      [ ""
      , "-- Sort ordering: U_Min ≤ _Top ≤ _Bot ≤ U_Max"
      , "axiom sort_order_1: U_Max → _Bot"
      , "axiom sort_order_2: _Bot  → _Top"
      , "axiom sort_order_3: _Top  → U_Min"
      ]
      ++ userSortOrderAxioms
      ++ [""]

    -- S_Max → S_Min for each user-declared sort
    userSortOrderAxioms :: [String]
    userSortOrderAxioms = map sortOrderAxiom userSorts
      where
        sortOrderAxiom s =
          "axiom " ++ IR.sortName s ++ "_sort_order: "
          ++ sortMaxName s ++ " → " ++ sortMinName s

    -- -----------------------------------------------------------------------
    -- User facts: assertions (ℙ, wrapped with _Top) and
    --             metafacts    (𝕌, wrapped with U_Min)
    -- -----------------------------------------------------------------------
    userAssertions =
      [ f
      | f <- IR.theoryFacts theory
      , IR.factKind f == IR.FactKindAssertion
      , not (IR.factIsInherited f)
      , not (IR.factIsMereologicalTranslation f)
      ]

    userMetafacts =
      [ f
      | f <- IR.theoryFacts theory
      , IR.factKind f == IR.FactKindMetafactsFact
      , not (IR.factIsInherited f)
      , not (IR.factIsMereologicalTranslation f)
      ]

    totalFacts = length userAssertions + length userMetafacts

    mkLabel :: Int -> String
    mkLabel idx = if totalFacts > 1 then "ax" ++ show idx ++ ": " else ""

    renderAssertion :: Int -> IR.Fact -> String
    renderAssertion idx fact =
      let fvs  = renderFreeVars (IR.factFreeVars fact)
          body = renderPropExpr (IR.factPropExpr fact)
      in "axiom " ++ mkLabel idx ++ "(_Top ∧ " ++ fvs ++ body ++ ") ↔ _Top"

    renderMetafact :: Int -> IR.Fact -> String
    renderMetafact idx fact =
      let fvs  = renderFreeVars (IR.factFreeVars fact)
          body = renderPropExpr (IR.factPropExpr fact)
      in "axiom " ++ mkLabel idx ++ "(U_Min ∧ " ++ fvs ++ body ++ ") ↔ U_Min"

    userFactAxioms =
         zipWith renderAssertion [1..] userAssertions
      ++ zipWith renderMetafact  [1 + length userAssertions..] userMetafacts

    -- -----------------------------------------------------------------------
    -- Free-variable rendering
    -- -----------------------------------------------------------------------
    renderFreeVars :: [IR.ResolvedVarDecl] -> String
    renderFreeVars [] = ""
    renderFreeVars vs = concatMap renderFreeVar vs ++ " "

    renderFreeVar :: IR.ResolvedVarDecl -> String
    renderFreeVar vd =
      let varName  = IR.resolvedVarName vd
          sortName = IR.sortName (IR.resolvedVarSort vd)
      in case sortName of
           "ℙ" -> "∀ " ++ varName ++ " : Prop, (_Bot → " ++ varName ++ ") ∧ (" ++ varName ++ " → _Top) → "
           "𝕌" -> "∀ " ++ varName ++ " : Prop, (U_Max → " ++ varName ++ ") ∧ (" ++ varName ++ " → U_Min) → "
           _   -> "∀ " ++ varName ++ " : " ++ sortName ++ ", "

-- ---------------------------------------------------------------------------
-- Expression rendering
-- ---------------------------------------------------------------------------

renderPropExpr :: IR.ResolvedPropExpr -> String
renderPropExpr (IR.ResolvedPropBicond lhs rests) =
  case rests of
    [] -> renderRightImpl lhs
    _  ->
      let left  = renderRightImpl lhs
          pairs = [ renderRightImpl (IR.resolvedPropRestRight r) | r <- rests ]
      in foldl (\acc p -> "(" ++ acc ++ " ↔ " ++ p ++ ")") left pairs

renderRightImpl :: IR.ResolvedRightImpl -> String
renderRightImpl (IR.ResolvedRightImpl lhs Nothing) =
  renderLeftImpl lhs
renderRightImpl (IR.ResolvedRightImpl lhs (Just (_, rhs))) =
  "(" ++ renderLeftImpl lhs ++ " → " ++ renderRightImpl rhs ++ ")"

renderLeftImpl :: IR.ResolvedLeftImpl -> String
renderLeftImpl (IR.ResolvedLeftImpl lhs []) =
  renderDisj lhs
renderLeftImpl (IR.ResolvedLeftImpl lhs rests) =
  let base  = renderDisj lhs
      steps = map (renderDisj . IR.resolvedLirRight) rests
  in foldl (\acc s -> "(" ++ s ++ " → " ++ acc ++ ")") base steps

renderDisj :: IR.ResolvedDisj -> String
renderDisj (IR.ResolvedDisj lhs []) = renderConj lhs
renderDisj (IR.ResolvedDisj lhs rests) =
  let parts = renderConj lhs : map (renderConj . IR.resolvedDisjRestRight) rests
  in "(" ++ intercalate " ∨ " parts ++ ")"

renderConj :: IR.ResolvedConj -> String
renderConj (IR.ResolvedConj lhs []) = renderNeg lhs
renderConj (IR.ResolvedConj lhs rests) =
  let parts = renderNeg lhs : map (renderNeg . IR.resolvedConjRestRight) rests
  in "(" ++ intercalate " ∧ " parts ++ ")"

renderNeg :: IR.ResolvedNeg -> String
renderNeg (IR.ResolvedNegNot inner) =
  "(" ++ renderNeg inner ++ " → _Bot)"
renderNeg (IR.ResolvedNegChild q) =
  renderQuantified q

renderQuantified :: IR.ResolvedQuantified -> String
renderQuantified (IR.ResolvedQuantified [] atom) =
  renderAtomicProp atom
renderQuantified (IR.ResolvedQuantified qs atom) =
  let quantStrings = map renderExplicitQuantifier qs
      body = renderAtomicProp atom
  in foldr (\q acc -> q ++ acc) body quantStrings

renderExplicitQuantifier :: IR.ResolvedQuantifier -> String
renderExplicitQuantifier (IR.ResolvedQForall vd) =
  let varName  = IR.resolvedVarName vd
      sortName = IR.sortName (IR.resolvedVarSort vd)
  in case sortName of
       "ℙ" -> "∀ " ++ varName ++ " : Prop, (_Bot → " ++ varName ++ ") ∧ (" ++ varName ++ " → _Top) → "
       "𝕌" -> "∀ " ++ varName ++ " : Prop, (U_Max → " ++ varName ++ ") ∧ (" ++ varName ++ " → U_Min) → "
       _   -> "∀ " ++ varName ++ " : " ++ sortName ++ ", "
renderExplicitQuantifier (IR.ResolvedQExists vd) =
  let varName  = IR.resolvedVarName vd
      sortName = IR.sortName (IR.resolvedVarSort vd)
  in case sortName of
       "ℙ" -> "∃ " ++ varName ++ " : Prop, (_Bot → " ++ varName ++ ") ∧ (" ++ varName ++ " → _Top) ∧ "
       "𝕌" -> "∃ " ++ varName ++ " : Prop, (U_Max → " ++ varName ++ ") ∧ (" ++ varName ++ " → U_Min) ∧ "
       _   -> "∃ " ++ varName ++ " : " ++ sortName ++ ", "

renderAtomicProp :: IR.ResolvedAtomicProp -> String
renderAtomicProp (IR.ResolvedAtomicConstant ref) = renderConstantRef ref
renderAtomicProp (IR.ResolvedAtomicTermPair tp)  = renderTermPair tp

renderConstantRef :: IR.ResolvedConstantRef -> String
renderConstantRef ref =
  case IR.resolvedConstRefName ref of
    "ℙ#min" -> "_Top"
    "ℙ#max" -> "_Bot"
    "𝕌#min" -> "U_Min"
    "𝕌#max" -> "U_Max"
    "⊤"     -> "_Top"
    "⊥"     -> "_Bot"
    other   -> other

-- ---------------------------------------------------------------------------
-- Term-pair rendering (relation-level: A - B, A × B, etc.)
-- Left-folding chain so operand-swap for - is correct.
-- ---------------------------------------------------------------------------

renderTermPair :: IR.ResolvedTermPair -> String
renderTermPair (IR.ResolvedTermPair lhs rights _) =
  renderTermPairChain (renderTerm lhs) rights

renderTermPairChain :: String -> [IR.ResolvedRelationFollowedByTerm] -> String
renderTermPairChain leftStr [] = leftStr
renderTermPairChain leftStr (rfbt : rest) =
  let op    = IR.resolvedRFTOp rfbt
      right = renderTerm (IR.resolvedRFTRight rfbt)
      combined = case op of
                   "+"  -> "(" ++ leftStr ++ " ∧ " ++ right ++ ")"
                   "×"  -> "(" ++ leftStr ++ " ∨ " ++ right ++ ")"
                   "-"  -> "(" ++ right ++ " → " ++ leftStr ++ ")"  -- A - B  ⟹  B → A
                   "∸"  -> "(" ++ leftStr ++ " ↔ " ++ right ++ ")"
                   "="  -> "(" ++ leftStr ++ " ↔ " ++ right ++ ")"
                   "≤"  -> "(" ++ leftStr ++ " → " ++ right ++ ")"
                   _    -> "(" ++ leftStr ++ " " ++ op ++ " " ++ right ++ ")"
  in renderTermPairChain combined rest

-- ---------------------------------------------------------------------------
-- Term rendering (factor-level arithmetic inside a term)
-- ---------------------------------------------------------------------------

renderTerm :: IR.ResolvedTerm -> String
renderTerm (IR.ResolvedTerm lhs [] _) = renderFactor lhs
renderTerm (IR.ResolvedTerm lhs rests _) =
  renderTermChain (renderFactor lhs) rests

renderTermChain :: String -> [IR.ResolvedOperationFollowedByFactor] -> String
renderTermChain leftStr [] = leftStr
renderTermChain leftStr (off : rest) =
  let op    = IR.resolvedOFFOp off
      right = renderFactor (IR.resolvedOFFRight off)
      combined = case op of
                   "+"  -> "(" ++ leftStr ++ " ∧ " ++ right ++ ")"
                   "×"  -> "(" ++ leftStr ++ " ∨ " ++ right ++ ")"
                   "-"  -> "(" ++ right ++ " → " ++ leftStr ++ ")"  -- A - B  ⟹  B → A
                   "∸"  -> "(" ++ leftStr ++ " ↔ " ++ right ++ ")"
                   _    -> "(" ++ leftStr ++ " " ++ op ++ " " ++ right ++ ")"
  in renderTermChain combined rest

renderFactor :: IR.ResolvedFactor -> String
renderFactor (IR.ResolvedFactor base [] _) = renderBaseTerm base
renderFactor (IR.ResolvedFactor base suffixes _) =
  -- When a sort constant (ℙ, 𝕌, 𝔻) is followed by a #min or #max suffix,
  -- the combination denotes a named limit object with its own Lean name.
  -- We resolve the pair here: e.g. ℙ#min → _Top, 𝕌#max → U_Max.
  case (base, suffixes) of
    (IR.ResolvedBTAtomic ref, IR.ResolvedSuffixSpecialOp attr : rest)
      | attr `elem` ["min", "max"] ->
          let baseName = IR.resolvedConstRefName ref
              leanName = case (baseName, attr) of
                ("ℙ", "min") -> "_Top"
                ("ℙ", "max") -> "_Bot"
                ("𝕌", "min") -> "U_Min"
                ("𝕌", "max") -> "U_Max"
                ("𝔻", "min") -> "U_Min"
                ("𝔻", "max") -> "U_Max"
                -- User-declared sort S: S#min → S_Min, S#max → S_Max
                (s, "min") -> s ++ "_Min"
                (s, "max") -> s ++ "_Max"
                _          -> baseName ++ "#" ++ attr
          in leanName ++ concatMap renderSuffix rest
    _ -> renderBaseTerm base ++ concatMap renderSuffix suffixes

renderSuffix :: IR.ResolvedTermSuffix -> String
renderSuffix (IR.ResolvedSuffixDotAttr attr) = "." ++ attr
renderSuffix (IR.ResolvedSuffixCall args)    =
  "(" ++ intercalate ", " (map renderTerm args) ++ ")"
renderSuffix (IR.ResolvedSuffixSpecialOp op) = op

renderBaseTerm :: IR.ResolvedBaseTerm -> String
renderBaseTerm (IR.ResolvedBTAtomic ref) =
  renderConstantRef ref
renderBaseTerm (IR.ResolvedBTParen expr) =
  "(" ++ renderPropExpr expr ++ ")"
renderBaseTerm (IR.ResolvedBTSingleton t) =
  "{" ++ renderTerm t ++ "}"
renderBaseTerm (IR.ResolvedBTEvaluationInTheory eit) =
  renderPropExpr (IR.resolvedEITOperand eit)
renderBaseTerm (IR.ResolvedBTProjectionToSort pts) =
  renderTerm (IR.resolvedPTOperand pts)
renderBaseTerm (IR.ResolvedBTProjectionToInterval pti) =
  renderTerm (IR.resolvedPTIOperand pti)
renderBaseTerm (IR.ResolvedBTGeneralizedSumOrProduct gsp) =
  renderTerm (IR.resolvedGSPOperand gsp)