-- | Export an Eidos mereological theory to Lean 4.
--
-- For theories using sort 𝕌 (the universe), mereological objects become Props.
-- Each such constant gets boundedness axioms: P → U_Min and U_Max → P.
-- Mereological operations map to logical connectives:
--   +  → ∧ (and)
--   ×  → ∨ (or)
--   -  → → (implication, with swapped operands: A - B becomes B → A)
--   ∸  → ↔ (iff)
-- Metafacts become axioms wrapped with U_Min ∧ ... ↔ U_Min.
-- Free variables are translated as forall quantifiers with boundedness conditions.
module Eidos.Export.LeanMereo
  ( exportToLeanMereo
  ) where

import Data.List (intercalate)
import qualified Eidos.IR as IR

-- ---------------------------------------------------------------------------
-- Top-level entry point
-- ---------------------------------------------------------------------------

exportToLeanMereo :: IR.Theory -> String
exportToLeanMereo theory =
  unlines $
       [ "-- Generated by Eidos compiler (mereological translation)"
       , "-- Theory: " ++ IR.theoryFullyQualifiedName theory
       , ""
       , "axiom U_Min : Prop"
       , "axiom U_Max : Prop"
       , ""
       ]
    ++ mereoAxioms
    ++ boundednessAxioms
    ++ metafactAxioms
  where
    mereoObjects :: [IR.MereologicalObject]
    mereoObjects =
      [ m
      | IR.EntityMereological m <- IR.theoryObjects theory
      , IR.mereoKind m == IR.MereologicalEntityKindMereological
      , IR.mereoOrigin m == IR.FromSignature
      , IR.mereoName m `notElem` ["U_Min", "U_Max", "⊤", "⊥"]
      ]

    mereoAxioms =
      [ "axiom " ++ IR.mereoName m ++ " : Prop"
      | m <- mereoObjects
      ]

    boundednessAxioms = concatMap boundednessForMereo mereoObjects

    boundednessForMereo :: IR.MereologicalObject -> [String]
    boundednessForMereo m =
      let name = IR.mereoName m
      in [ "axiom " ++ name ++ "_min: " ++ name ++ " → U_Min"
         , "axiom " ++ name ++ "_max: U_Max → " ++ name
         ]

    userMetafacts =
      [ f
      | f <- IR.theoryFacts theory
      , IR.factKind f == IR.FactKindMetafactsFact
      , not (IR.factIsInherited f)
      , not (IR.factIsMereologicalTranslation f)
      ]

    metafactAxioms = zipWith renderFact [1..] userMetafacts

    renderFact :: Int -> IR.Fact -> String
    renderFact idx fact =
      let label = if length userMetafacts > 1
                    then "ax" ++ show idx ++ ": "
                    else ""
          freeVarsStr = renderFreeVars (IR.factFreeVars fact)
          body = renderPropExpr (IR.factPropExpr fact)
      in "axiom " ++ label ++ "(U_Min ∧ " ++ freeVarsStr ++ body ++ ") ↔ U_Min"

    renderFreeVars :: [IR.ResolvedVarDecl] -> String
    renderFreeVars [] = ""
    renderFreeVars vars =
      let varStrings = map renderFreeVar vars
      in concat varStrings ++ " "

    renderFreeVar :: IR.ResolvedVarDecl -> String
    renderFreeVar vd =
      let varName = IR.resolvedVarName vd
          sortName = IR.sortName (IR.resolvedVarSort vd)
      in case sortName of
           "𝕌" -> "∀ " ++ varName ++ " : Prop, (U_Max → " ++ varName ++ ") ∧ (" ++ varName ++ " → U_Min) → "
           "ℙ" -> "∀ " ++ varName ++ " : Prop, (_Bot → " ++ varName ++ ") ∧ (" ++ varName ++ " → _Top) → "
           _ -> "∀ " ++ varName ++ " : " ++ sortName ++ ", "

-- ---------------------------------------------------------------------------
-- Expression rendering with correct operand swap for difference (-)
-- ---------------------------------------------------------------------------

renderPropExpr :: IR.ResolvedPropExpr -> String
renderPropExpr (IR.ResolvedPropBicond lhs rests) =
  let left = renderRightImpl lhs
  in case rests of
       [] -> left
       _ -> let pairs = [ renderRightImpl (IR.resolvedPropRestRight r) | r <- rests ]
            in foldl (\acc p -> "(" ++ acc ++ " ↔ " ++ p ++ ")") left pairs

renderRightImpl :: IR.ResolvedRightImpl -> String
renderRightImpl (IR.ResolvedRightImpl lhs Nothing) =
  renderLeftImpl lhs
renderRightImpl (IR.ResolvedRightImpl lhs (Just (_, rhs))) =
  let l = renderLeftImpl lhs
      r = renderRightImpl rhs
  in "(" ++ l ++ " → " ++ r ++ ")"

renderLeftImpl :: IR.ResolvedLeftImpl -> String
renderLeftImpl (IR.ResolvedLeftImpl lhs []) =
  renderDisj lhs
renderLeftImpl (IR.ResolvedLeftImpl lhs rests) =
  let base = renderDisj lhs
      steps = map (renderDisj . IR.resolvedLirRight) rests
  in foldl (\acc s -> "(" ++ s ++ " → " ++ acc ++ ")") base steps

renderDisj :: IR.ResolvedDisj -> String
renderDisj (IR.ResolvedDisj lhs []) = renderConj lhs
renderDisj (IR.ResolvedDisj lhs rests) =
  let parts = renderConj lhs : map (renderConj . IR.resolvedDisjRestRight) rests
  in "(" ++ intercalate " ∨ " parts ++ ")"

renderConj :: IR.ResolvedConj -> String
renderConj (IR.ResolvedConj lhs []) = renderNeg lhs
renderConj (IR.ResolvedConj lhs rests) =
  let parts = renderNeg lhs : map (renderNeg . IR.resolvedConjRestRight) rests
  in "(" ++ intercalate " ∧ " parts ++ ")"

renderNeg :: IR.ResolvedNeg -> String
renderNeg (IR.ResolvedNegNot inner) =
  let innerStr = renderNeg inner
  in "(" ++ innerStr ++ " → U_Min)"
renderNeg (IR.ResolvedNegChild q) = renderQuantified q

renderQuantified :: IR.ResolvedQuantified -> String
renderQuantified (IR.ResolvedQuantified [] atom) =
  renderAtomicProp atom
renderQuantified (IR.ResolvedQuantified qs atom) =
  let quantStrings = map renderExplicitQuantifier qs
      body = renderAtomicProp atom
  in foldr (\q acc -> q ++ "(" ++ acc ++ ")") body quantStrings

renderExplicitQuantifier :: IR.ResolvedQuantifier -> String
renderExplicitQuantifier (IR.ResolvedQForall vd) =
  let varName = IR.resolvedVarName vd
      sortName = IR.sortName (IR.resolvedVarSort vd)
  in case sortName of
       "𝕌" -> "∀ " ++ varName ++ " : Prop, (U_Max → " ++ varName ++ ") ∧ (" ++ varName ++ " → U_Min) → "
       "ℙ" -> "∀ " ++ varName ++ " : Prop, (_Bot → " ++ varName ++ ") ∧ (" ++ varName ++ " → _Top) → "
       _ -> "∀ " ++ varName ++ " : " ++ sortName ++ ", "
renderExplicitQuantifier (IR.ResolvedQExists vd) =
  let varName = IR.resolvedVarName vd
      sortName = IR.sortName (IR.resolvedVarSort vd)
  in case sortName of
       "𝕌" -> "∃ " ++ varName ++ " : Prop, (U_Max → " ++ varName ++ ") ∧ (" ++ varName ++ " → U_Min) ∧ "
       "ℙ" -> "∃ " ++ varName ++ " : Prop, (_Bot → " ++ varName ++ ") ∧ (" ++ varName ++ " → _Top) ∧ "
       _ -> "∃ " ++ varName ++ " : " ++ sortName ++ ", "

renderAtomicProp :: IR.ResolvedAtomicProp -> String
renderAtomicProp (IR.ResolvedAtomicConstant ref) =
  renderConstantRef ref
renderAtomicProp (IR.ResolvedAtomicTermPair tp) =
  renderTermPair tp

renderConstantRef :: IR.ResolvedConstantRef -> String
renderConstantRef ref =
  let name = IR.resolvedConstRefName ref
  in case name of
       "𝕌#min" -> "U_Min"
       "𝕌#max" -> "U_Max"
       "⊤"     -> "U_Min"
       "⊥"     -> "U_Max"
       _        -> name

-- Key fix: Swap operands for difference (-) operation
renderTermPair :: IR.ResolvedTermPair -> String
renderTermPair (IR.ResolvedTermPair lhs rights _) =
  let leftStr = renderTerm lhs
  in case rights of
       [] -> leftStr
       _ -> let rightStrs = map (renderRelationFollowedByTermWithLeft leftStr) rights
            in "(" ++ intercalate " " (leftStr : rightStrs) ++ ")"

renderRelationFollowedByTermWithLeft :: String -> IR.ResolvedRelationFollowedByTerm -> String
renderRelationFollowedByTermWithLeft leftStr rfbt =
  let op = IR.resolvedRFTOp rfbt
      right = renderTerm (IR.resolvedRFTRight rfbt)
  in case op of
       "+"  -> "∧ " ++ right
       "×"  -> "∨ " ++ right
       "-"  -> right ++ " → " ++ leftStr   -- A - B becomes B → A
       "∸"  -> "↔ " ++ right
       "="  -> "↔ " ++ right
       "≤"  -> "→ " ++ right
       _    -> op ++ " " ++ right

renderTerm :: IR.ResolvedTerm -> String
renderTerm (IR.ResolvedTerm lhs [] _) = renderFactor lhs
renderTerm (IR.ResolvedTerm lhs rests _) =
  let base = renderFactor lhs
  in case rests of
       [] -> base
       _ -> let ops = map (renderOpFactorWithLeft base) rests
            in "(" ++ intercalate " " (base : ops) ++ ")"

renderOpFactorWithLeft :: String -> IR.ResolvedOperationFollowedByFactor -> String
renderOpFactorWithLeft leftStr off =
  let op = IR.resolvedOFFOp off
      right = renderFactor (IR.resolvedOFFRight off)
  in case op of
       "+"  -> "∧ " ++ right
       "×"  -> "∨ " ++ right
       "-"  -> right ++ " → " ++ leftStr   -- A - B becomes B → A
       "∸"  -> "↔ " ++ right
       _    -> op ++ " " ++ right

renderFactor :: IR.ResolvedFactor -> String
renderFactor (IR.ResolvedFactor base [] _) = renderBaseTerm base
renderFactor (IR.ResolvedFactor base suffixes _) =
  let baseStr = renderBaseTerm base
  in case suffixes of
       [] -> baseStr
       _ -> baseStr ++ concatMap renderSuffix suffixes

renderSuffix :: IR.ResolvedTermSuffix -> String
renderSuffix (IR.ResolvedSuffixDotAttr attr) = "." ++ attr
renderSuffix (IR.ResolvedSuffixCall args) =
  "(" ++ intercalate ", " (map renderTerm args) ++ ")"
renderSuffix (IR.ResolvedSuffixSpecialOp op) = op

renderBaseTerm :: IR.ResolvedBaseTerm -> String
renderBaseTerm (IR.ResolvedBTAtomic ref) =
  renderConstantRef ref
renderBaseTerm (IR.ResolvedBTParen expr) =
  let inner = renderPropExpr expr
  in "(" ++ inner ++ ")"
renderBaseTerm (IR.ResolvedBTSingleton t) =
  "{" ++ renderTerm t ++ "}"
renderBaseTerm (IR.ResolvedBTEvaluationInTheory eit) =
  renderPropExpr (IR.resolvedEITOperand eit)
renderBaseTerm (IR.ResolvedBTProjectionToSort pts) =
  renderTerm (IR.resolvedPTOperand pts)
renderBaseTerm (IR.ResolvedBTProjectionToInterval pti) =
  renderTerm (IR.resolvedPTIOperand pti)
renderBaseTerm (IR.ResolvedBTGeneralizedSumOrProduct gsp) =
  renderTerm (IR.resolvedGSPOperand gsp)