-- | Export an Eidos propositional theory to Lean 4 using the \"all Props\" strategy.
--
-- Every ℙ-kinded object in the signature becomes an @axiom : Prop@.
-- Each such constant also gets boundedness axioms: P → _Top and _Bot → P.
-- Every assertion becomes an axiom @(_Top ∧ formula) ↔ _Top@.
-- Bracketed variables [X : ℙ] become @∀ X : Prop, (_Bot → X) ∧ (X → _Top) → ...@
-- Explicit quantifiers ∀ and ∃ are handled similarly with boundedness conditions.
-- Negation ¬P is rendered as @(P → _Bot)@.
-- ⊤ / ⊥ in the source become @_Top@ / @_Bot@.
module Eidos.Export.LeanProps
  ( exportToLeanProps
  ) where

import Data.List (intercalate)
import qualified Eidos.IR as IR

-- ---------------------------------------------------------------------------
-- Top-level entry point
-- ---------------------------------------------------------------------------

-- | Render a fully-built 'IR.Theory' as a Lean 4 file string using the
--   @--lean_using_props@ strategy.
exportToLeanProps :: IR.Theory -> String
exportToLeanProps theory =
  unlines $
       [ "-- Generated by Eidos compiler"
       , "-- Theory: " ++ IR.theoryFullyQualifiedName theory
       , ""
       , "axiom _Top : Prop"
       , "axiom _Bot : Prop"
       , ""
       ]
    ++ propAxioms
    ++ boundednessAxioms
    ++ assertionAxioms
  where
    -- Collect all ℙ-kinded mereological objects that were declared in the
    -- signature (FromSignature origin, PropositionClass kind).
    props :: [IR.MereologicalObject]
    props =
      [ m
      | IR.EntityMereological m <- IR.theoryObjects theory
      , IR.mereoKind m == IR.MereologicalEntityKindProposition
      , IR.mereoOrigin m == IR.FromSignature
      , IR.mereoName m `notElem` ["_Top", "_Bot", "⊤", "⊥", "ℙ#min", "ℙ#max"]
      ]

    -- Declaration axioms for each proposition constant
    propAxioms =
      [ "axiom " ++ IR.mereoName m ++ " : Prop"
      | m <- props
      ]

    -- Boundedness axioms: P → _Top and _Bot → P
    boundednessAxioms = concatMap boundednessForProp props

    boundednessForProp :: IR.MereologicalObject -> [String]
    boundednessForProp m =
      let name = IR.mereoName m
      in [ "axiom " ++ name ++ "_top: " ++ name ++ " → _Top"
         , "axiom " ++ name ++ "_bot: _Bot → " ++ name
         ]

    -- Collect user assertions (not inherited, not mereological translations)
    userAssertions =
      [ f
      | f <- IR.theoryFacts theory
      , IR.factKind f == IR.FactKindAssertion
      , not (IR.factIsInherited f)
      , not (IR.factIsMereologicalTranslation f)
      ]

    -- Render each assertion, numbering them when there are multiple.
    assertionAxioms = zipWith renderFact [1..] userAssertions

    renderFact :: Int -> IR.Fact -> String
    renderFact idx fact =
      let label = if length userAssertions > 1
                    then "ax" ++ show idx ++ ": "
                    else ""
          freeVarsStr = renderFreeVars (IR.factFreeVars fact)
          body = renderPropExpr (IR.factPropExpr fact)
      in "axiom " ++ label ++ "(_Top ∧ " ++ freeVarsStr ++ body ++ ") ↔ _Top"

    renderFreeVars :: [IR.ResolvedVarDecl] -> String
    renderFreeVars [] = ""
    renderFreeVars vars =
      let varStrings = map renderFreeVar vars
      in concat varStrings ++ " "

    -- Render a bracketed free variable [X : ℙ] as a forall with boundedness
    renderFreeVar :: IR.ResolvedVarDecl -> String
    renderFreeVar vd =
      let varName = IR.resolvedVarName vd
          sortName = IR.sortName (IR.resolvedVarSort vd)
      in case sortName of
           "ℙ" -> "∀ " ++ varName ++ " : Prop, (_Bot → " ++ varName ++ ") ∧ (" ++ varName ++ " → _Top) → "
           _ -> "∀ " ++ varName ++ " : " ++ sortName ++ ", "

-- ---------------------------------------------------------------------------
-- Expression rendering
-- ---------------------------------------------------------------------------

renderPropExpr :: IR.ResolvedPropExpr -> String
renderPropExpr (IR.ResolvedPropBicond lhs rests) =
  case rests of
    [] -> renderRightImpl lhs
    _  ->
      let left = renderRightImpl lhs
          pairs = [ renderRightImpl (IR.resolvedPropRestRight r) | r <- rests ]
      in foldl (\acc p -> "(" ++ acc ++ " ↔ " ++ p ++ ")") left pairs

renderRightImpl :: IR.ResolvedRightImpl -> String
renderRightImpl (IR.ResolvedRightImpl lhs Nothing) =
  renderLeftImpl lhs
renderRightImpl (IR.ResolvedRightImpl lhs (Just (_, rhs))) =
  "(" ++ renderLeftImpl lhs ++ " → " ++ renderRightImpl rhs ++ ")"

renderLeftImpl :: IR.ResolvedLeftImpl -> String
renderLeftImpl (IR.ResolvedLeftImpl lhs []) =
  renderDisj lhs
renderLeftImpl (IR.ResolvedLeftImpl lhs rests) =
  let base = renderDisj lhs
      steps = map (renderDisj . IR.resolvedLirRight) rests
  in foldl (\acc s -> "(" ++ s ++ " → " ++ acc ++ ")") base steps

renderDisj :: IR.ResolvedDisj -> String
renderDisj (IR.ResolvedDisj lhs []) = renderConj lhs
renderDisj (IR.ResolvedDisj lhs rests) =
  let parts = renderConj lhs : map (renderConj . IR.resolvedDisjRestRight) rests
  in "(" ++ intercalate " ∨ " parts ++ ")"

renderConj :: IR.ResolvedConj -> String
renderConj (IR.ResolvedConj lhs []) = renderNeg lhs
renderConj (IR.ResolvedConj lhs rests) =
  let parts = renderNeg lhs : map (renderNeg . IR.resolvedConjRestRight) rests
  in "(" ++ intercalate " ∧ " parts ++ ")"

renderNeg :: IR.ResolvedNeg -> String
renderNeg (IR.ResolvedNegNot inner) =
  "(" ++ renderNeg inner ++ " → _Bot)"
renderNeg (IR.ResolvedNegChild q) =
  renderQuantified q

-- Quantified expressions in the body (from explicit ∀/∃ in the source)
renderQuantified :: IR.ResolvedQuantified -> String
renderQuantified (IR.ResolvedQuantified [] atom) =
  renderAtomicProp atom
renderQuantified (IR.ResolvedQuantified qs atom) =
  let quantStrings = map renderExplicitQuantifier qs
      body = renderAtomicProp atom
  in foldr (\q acc -> q ++ acc) body quantStrings

-- Render explicit quantifier with boundedness condition
renderExplicitQuantifier :: IR.ResolvedQuantifier -> String
renderExplicitQuantifier (IR.ResolvedQForall vd) =
  let varName = IR.resolvedVarName vd
      sortName = IR.sortName (IR.resolvedVarSort vd)
  in case sortName of
       "ℙ" -> "∀ " ++ varName ++ " : Prop, (_Bot → " ++ varName ++ ") ∧ (" ++ varName ++ " → _Top) → "
       _ -> "∀ " ++ varName ++ " : " ++ sortName ++ ", "
renderExplicitQuantifier (IR.ResolvedQExists vd) =
  let varName = IR.resolvedVarName vd
      sortName = IR.sortName (IR.resolvedVarSort vd)
  in case sortName of
       "ℙ" -> "∃ " ++ varName ++ " : Prop, (_Bot → " ++ varName ++ ") ∧ (" ++ varName ++ " → _Top) ∧ "
       _ -> "∃ " ++ varName ++ " : " ++ sortName ++ ", "

renderAtomicProp :: IR.ResolvedAtomicProp -> String
renderAtomicProp (IR.ResolvedAtomicConstant ref) =
  renderConstantRef ref
renderAtomicProp (IR.ResolvedAtomicTermPair tp) =
  renderTermPair tp

renderConstantRef :: IR.ResolvedConstantRef -> String
renderConstantRef ref =
  let name = IR.resolvedConstRefName ref
  in case name of
       "ℙ#min" -> "_Top"   -- ℙ#min is ⊤ (maximum/truth)
       "ℙ#max" -> "_Bot"   -- ℙ#max is ⊥ (minimum/falsity)
       "⊤"     -> "_Top"
       "⊥"     -> "_Bot"
       _        -> name

renderTermPair :: IR.ResolvedTermPair -> String
renderTermPair (IR.ResolvedTermPair lhs [] _) =
  renderTerm lhs
renderTermPair (IR.ResolvedTermPair lhs rights _) =
  let l = renderTerm lhs
      rs = map renderRelationFollowedByTerm rights
  in "(" ++ intercalate " " (l : rs) ++ ")"

renderRelationFollowedByTerm :: IR.ResolvedRelationFollowedByTerm -> String
renderRelationFollowedByTerm rfbt =
  IR.resolvedRFTOp rfbt ++ " " ++ renderTerm (IR.resolvedRFTRight rfbt)

renderTerm :: IR.ResolvedTerm -> String
renderTerm (IR.ResolvedTerm lhs [] _) = renderFactor lhs
renderTerm (IR.ResolvedTerm lhs rests _) =
  let base   = renderFactor lhs
      others = map renderOpFactor rests
  in "(" ++ intercalate " " (base : others) ++ ")"

renderOpFactor :: IR.ResolvedOperationFollowedByFactor -> String
renderOpFactor off =
  IR.resolvedOFFOp off ++ " " ++ renderFactor (IR.resolvedOFFRight off)

renderFactor :: IR.ResolvedFactor -> String
renderFactor (IR.ResolvedFactor base [] _) = renderBaseTerm base
renderFactor (IR.ResolvedFactor base suffixes _) =
  renderBaseTerm base ++ concatMap renderSuffix suffixes

renderSuffix :: IR.ResolvedTermSuffix -> String
renderSuffix (IR.ResolvedSuffixDotAttr attr) = "." ++ attr
renderSuffix (IR.ResolvedSuffixCall args)    =
  "(" ++ intercalate ", " (map renderTerm args) ++ ")"
renderSuffix (IR.ResolvedSuffixSpecialOp op) = op

renderBaseTerm :: IR.ResolvedBaseTerm -> String
renderBaseTerm (IR.ResolvedBTAtomic ref) =
  renderConstantRef ref
renderBaseTerm (IR.ResolvedBTParen expr) =
  "(" ++ renderPropExpr expr ++ ")"
renderBaseTerm (IR.ResolvedBTSingleton t) =
  "{" ++ renderTerm t ++ "}"
renderBaseTerm (IR.ResolvedBTEvaluationInTheory eit) =
  renderPropExpr (IR.resolvedEITOperand eit)
renderBaseTerm (IR.ResolvedBTProjectionToSort pts) =
  renderTerm (IR.resolvedPTOperand pts)
renderBaseTerm (IR.ResolvedBTProjectionToInterval pti) =
  renderTerm (IR.resolvedPTIOperand pti)
renderBaseTerm (IR.ResolvedBTGeneralizedSumOrProduct gsp) =
  renderTerm (IR.resolvedGSPOperand gsp)