-- | Core expression and document types for Lean 4 export.
--
-- This module is imported by both 'Eidos.Export.LeanAxiomSet' and
-- 'Eidos.Export.LeanProps'.  Keeping it separate avoids a circular
-- dependency and makes the expression language easy to test in isolation.
module Eidos.Export.LeanExpr
  ( -- * Document structure
    LeanDoc (..)
  , LeanDecl (..)
    -- * Axioms
  , LeanAxiom (..)
    -- * Expression language
  , LeanExpr (..)
    -- * Rendering
  , renderLeanDoc
  , renderLeanExpr
  ) where

-- ---------------------------------------------------------------------------
-- Document structure
-- ---------------------------------------------------------------------------

-- | A complete Lean 4 document ready to be printed.
data LeanDoc = LeanDoc
  { leanDocTheoryName :: String
  , leanDocDecls      :: [LeanDecl]
  } deriving (Eq, Show)

-- | A single top-level item in a Lean 4 file.
data LeanDecl
  = DeclComment  String    -- ^ @-- comment@
  | DeclBlankLine           -- ^ empty line
  | DeclAxiom    LeanAxiom -- ^ @axiom name : body@
  deriving (Eq, Show)

-- ---------------------------------------------------------------------------
-- Axioms
-- ---------------------------------------------------------------------------

-- | An @axiom@ statement with a name and a type expression.
data LeanAxiom = LeanAxiom
  { axiomName :: String
  , axiomType :: LeanExpr
  } deriving (Eq, Show)

-- ---------------------------------------------------------------------------
-- Expression language
-- ---------------------------------------------------------------------------

-- | A Lean 4 proposition (the expression language we need).
data LeanExpr
  = LProp
    -- ^ @Prop@
  | LVar String
    -- ^ Atomic name.
  | LApp LeanExpr [LeanExpr]
    -- ^ Function application.
  | LImpl LeanExpr LeanExpr
    -- ^ @A → B@
  | LConj LeanExpr LeanExpr
    -- ^ @A ∧ B@
  | LDisj LeanExpr LeanExpr
    -- ^ @A ∨ B@
  | LBicond LeanExpr LeanExpr
    -- ^ @A ↔ B@
  | LForall String LeanExpr LeanExpr
    -- ^ @∀ x : T, body@  (symbol style)
  | LForallKw String LeanExpr LeanExpr
    -- ^ @forall x : T, body@  (keyword style)
  | LExists String LeanExpr LeanExpr
    -- ^ @∃ x : T, body@
  | LEq LeanExpr LeanExpr
    -- ^ @A = B@
  | LIsWithinBounds String String String
    -- ^ @LIsWithinBounds lo var hi@ renders as
    --   @(IsWithinBounds lo hi var)@.
    --   All three fields are variable /names/ (not expressions), kept as
    --   'String' because 'IsWithinBounds' is always applied to atomic names
    --   in our encoding.
  | LIsIndividual String String String
    -- ^ @LIsIndividual lo var hi@ renders as
    --   @(IsIndividual lo hi var)@.
    --   Guards first-order (individual) quantification.  In the current
    --   version 'IsIndividual' is defined as always true (@\_ _ _ => True@)
    --   but the hook is in place for future refinement.
  | LBoundedForall String String String LeanExpr
    -- ^ @LBoundedForall var lo hi body@ renders as
    --   @forall var : Prop, (IsWithinBounds lo hi var) → body@.
    --   This is the single most common pattern in the output; making it a
    --   first-class node allows tests to pattern-match on it directly and
    --   opens the door to alternative renderings (symbol style, future
    --   macro syntax).
  | LProjectIntoInterval LeanExpr LeanExpr LeanExpr
    -- ^ @ProjectIntoInterval x lo hi@
  deriving (Eq, Show)

-- ---------------------------------------------------------------------------
-- Rendering
-- ---------------------------------------------------------------------------

-- | Render a 'LeanDoc' to Lean 4 source text.
renderLeanDoc :: LeanDoc -> String
renderLeanDoc doc =
  unlines $
       [ "-- Generated by Eidos compiler"
       , "-- Theory: " ++ leanDocTheoryName doc
       , ""
       , "def IsWithinBounds (lo hi x : Prop) : Prop := (hi → x) ∧ (x → lo)"
       , "def ProjectIntoInterval (x lo hi : Prop) : Prop := (x ∧ lo) ∨ hi"
       , "def IsIndividual (lo hi x : Prop) : Prop := True"
       , ""
       ]
    ++ map renderDecl (leanDocDecls doc)

renderDecl :: LeanDecl -> String
renderDecl DeclBlankLine   = ""
renderDecl (DeclComment c) = "-- " ++ c
renderDecl (DeclAxiom ax)  = renderAxiom ax

renderAxiom :: LeanAxiom -> String
renderAxiom (LeanAxiom name ty) =
  "axiom " ++ name ++ ": " ++ renderLeanExpr ty

-- | Render a 'LeanExpr' to a Lean 4 string.
renderLeanExpr :: LeanExpr -> String
renderLeanExpr LProp =
  "Prop"
renderLeanExpr (LVar n) =
  n
renderLeanExpr (LApp f args) =
  "(" ++ renderLeanExpr f ++ " " ++ unwords (map renderLeanExpr args) ++ ")"
renderLeanExpr (LImpl a b) =
  "(" ++ renderLeanExpr a ++ " → " ++ renderLeanExpr b ++ ")"
renderLeanExpr (LConj a b) =
  "(" ++ renderLeanExpr a ++ " ∧ " ++ renderLeanExpr b ++ ")"
renderLeanExpr (LDisj a b) =
  "(" ++ renderLeanExpr a ++ " ∨ " ++ renderLeanExpr b ++ ")"
renderLeanExpr (LBicond a b) =
  "(" ++ renderLeanExpr a ++ " ↔ " ++ renderLeanExpr b ++ ")"
renderLeanExpr (LForall x ty body) =
  "∀ " ++ x ++ " : " ++ renderLeanExpr ty ++ ", " ++ renderLeanExpr body
renderLeanExpr (LForallKw x ty body) =
  "forall " ++ x ++ " : " ++ renderLeanExpr ty ++ ", " ++ renderLeanExpr body
renderLeanExpr (LExists x ty body) =
  "∃ " ++ x ++ " : " ++ renderLeanExpr ty ++ ", " ++ renderLeanExpr body
renderLeanExpr (LEq a b) =
  renderLeanExpr a ++ " = " ++ renderLeanExpr b
renderLeanExpr (LIsWithinBounds lo v hi) =
  "(IsWithinBounds " ++ lo ++ " " ++ hi ++ " " ++ v ++ ")"
renderLeanExpr (LIsIndividual lo v hi) =
  "(IsIndividual " ++ lo ++ " " ++ hi ++ " " ++ v ++ ")"
renderLeanExpr (LBoundedForall var lo hi body) =
  "forall " ++ var ++ " : Prop, "
    ++ renderLeanExpr (LIsWithinBounds lo var hi)
    ++ " → " ++ renderLeanExpr body
renderLeanExpr (LProjectIntoInterval x lo hi) =
  "(ProjectIntoInterval "
    ++ renderLeanExpr x ++ " "
    ++ renderLeanExpr lo ++ " "
    ++ renderLeanExpr hi ++ ")"
